Add event parser class
wintercms/wn-docs-plugin pull request #2
Opened 2021-03-22 03:29 UTC by mjauvin

Extracts all the events doc blocks and returns the doc block comment and where it is triggered.

2021-03-22 03:46 UTC, bennothommo requested changes

2021-03-22 03:46 UTC, bennothommo commented on classes/EventParser.php
> +    }
@mjauvin I would suggest the first parameter be the path to look for PHP files within, and use that as opposed to the hard-coded paths you have here.

2021-03-22 03:46 UTC, bennothommo commented on classes/EventParser.php
> +    public static function getEvent($file, $prefix=null)
```suggestion
    public static function getEvent($file, $prefix = null)
```

2021-03-22 03:46 UTC, bennothommo commented on classes/EventParser.php
> +    public static function getEvent($file, $prefix=null)
Also, I wouldn't mind seeing if we can use the `ReflectionDocBlock` class from `phpDocumentor` for this, after extracting the event docblocks themselves. That class will properly parse the docblock and provide the attributes in an easy-to-use format for us.

2021-03-22 13:16 UTC, mjauvin commented on classes/EventParser.php
> +    public static function getEvent($file, $prefix=null)
@bennothommo I was thinking the actual parsing would be done by another method which would call `getEvents()`.

2021-03-26 02:05 UTC, mjauvin commented
![Screenshot from 2021-03-25 22-04-57](https://user-images.githubusercontent.com/2013630/112566905-35bbda80-8db6-11eb-8707-4b739809a51c.png)

2021-04-04 13:19 UTC, mjauvin commented
@LukeTowers @bennothommo any objection to merge this?

2021-04-05 05:23 UTC, bennothommo requested changes
@mjauvin I'd prefer us to keep the regex delimiters consistent.

2021-04-05 05:23 UTC, bennothommo commented on classes/EventParser.php
> +        if (!preg_match_all('| +/\*\*\s+\* @event.+\*/|Us', $data, $matches)) {
```suggestion
        if (!preg_match_all('/ +/\*\*\s+\* @event.+\*\\//Us', $data, $matches)) {
```

2021-04-05 05:23 UTC, bennothommo commented on classes/EventParser.php
> +        if (preg_match('|@event (.+?)$|m', $doc, $match)) {
```suggestion
        if (preg_match('/@event (.+?)$/m', $doc, $match)) {
```

2021-04-05 05:23 UTC, bennothommo commented on classes/EventParser.php
> +        if (preg_match_all('|@param (.+?)$|m', $doc, $matches)) {
```suggestion
        if (preg_match_all('/@param (.+?)$/m', $doc, $matches)) {
```

2021-04-05 05:23 UTC, bennothommo commented on classes/EventParser.php
> +        if (preg_match('|@since (.+?)$|m', $doc, $match)) {
```suggestion
        if (preg_match('/@since (.+?)$/m', $doc, $match)) {
```

2021-04-05 05:25 UTC, bennothommo commented
@mjauvin Before merging, would you be able to do some unit tests? I'd be especially interested to see if it's parsing params that span multiple lines?

2021-04-05 12:13 UTC, mjauvin commented on classes/EventParser.php
> +        if (!preg_match_all('| +/\*\*\s+\* @event.+\*/|Us', $data, $matches)) {
I find it much cleaner to change the default regex delimiter character when it's used elsewhere in the regex instead of escaping it.

2021-04-05 12:17 UTC, mjauvin commented
@bennothommo why would a tag span multiple lines? The @param, @since and @event definitely won't.

2021-04-05 12:23 UTC, bennothommo commented
@mjauvin "event" and "since" likely won't, but it's fairly common for the param tag to span a couple of lines for more complex parameters, or for listing potential parameter values.

2021-04-05 12:30 UTC, mjauvin commented
@bennothommo can you give an example of this? How would it be delimited, by an empty line?

2021-04-05 13:18 UTC, bennothommo commented
@mjauvin This is one example:
https://github.com/wintercms/winter/blob/develop/modules/system/classes/SourceManifest.php#L419-L420

It would either be delimited by another tag being defined (like say another `@param` or `@since` tag), or it would be delimited by the event doc block ending.

I would say, however, that I'm sure the ReflectionDocBlock library would have this covered if you were to use that instead.

2021-04-05 13:42 UTC, mjauvin commented
Fair enough @bennothommo.

I am not using the ReflectionDocBlock library because the format for our Events doc blocks is not really compatible with the standard format.

2021-04-05 13:49 UTC, bennothommo commented
@mjauvin Fair enough if that's the case, but if you get stuck, it might be worth having a browse through their code and see if they do things differently.

2021-04-05 13:51 UTC, mjauvin commented
I'll modify the @param parser to handle multi-lines.

2021-04-19 14:37 UTC, bennothommo approved these changes

2021-04-19 14:37 UTC, merged